server:
  port: 8080

# 开启驼峰命名和日志
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias?SSL=flase&Timezone=UTC
    username: root
    password: 123456
#  配置文件上传大小的限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucketName: web-hl


#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug



